version: '3'

services:
  web-prod:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"

  web-qa:
    image: nginx:alpine
    restart: always
    ports:
      - "8080:80"

  web-dev:
    image: nginx:alpine
    restart: always
    ports:
      - "8081:80"